### ISSUE TITLE
Github action pushing package error

### ISSUE THREAD

**Issue by notone0010** [notone0010/provider-ksyun#10]
#2
 
Hi, @jastang 

I have changed the access keys with Robot Account Token based on the suggestion of [reposity-permisstions](https://docs.upbound.io/concepts/accounts/teams/#manage-repository-permissions). However, I still encounter the same error that prints **authentication required**, when the step, Login To Upbound, displays "Login Succeeded!".

The Login to Upbound step output:

```
Run docker/login-action@v2
  with:
    registry: xpkg.upbound.io
    username: ***
    password: ***
    ecr: auto
    logout: true
  env:
    GO_VERSION: 1.19
    GOLANGCI_VERSION: v1.50.0
    DOCKER_BUILDX_VERSION: v0.8.[2](https://github.com/notone0010/provider-ksyun/actions/runs/6651657167/job/18105979018#step:4:2)
    UPBOUND_MARKETPLACE_PUSH_ROBOT_USR: ***
Logging into xpkg.upbound.io...
Login Succeeded!
```

The Pushing Artifacts step output:
```
Run make publish BRANCH_NAME=${GITHUB_REF##*/}
02:25:02 [ .. ] Skipping image publish for xpkg.upbound.io/notone/provider-ksyun:v0.1.1-23.g4fcfb95
Publish is deferred to xpkg machinery
02:25:02 [ OK ] Image publish skipped for xpkg.upbound.io/notone/provider-ksyun:v0.1.1-23.g4fcfb95
02:25:02 [ .. ] Pushing package xpkg.upbound.io/notone/provider-ksyun:v0.1.1-23.g4fcfb95
up: error: xpkg.pushCmd.Run(): POST https://xpkg.upbound.io/v2/notone/provider-ksyun/blobs/uploads/: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:notone/provider-ksyun Type:repository] map[Action:push Class: Name:notone/provider-ksyun Type:repository]]
02:25:06 [FAIL]
make[1]: *** [build/makelib/xpkg.mk:[10](https://github.com/notone0010/provider-ksyun/actions/runs/6651657167/job/18105979018#step:14:11)5: xpkg.release.publish.xpkg.upbound.io/notone.provider-ksyun] Error 1
make: *** [build/makelib/common.mk:4[11](https://github.com/notone0010/provider-ksyun/actions/runs/6651657167/job/18105979018#step:14:12): publish] Error 2
Error: Process completed with exit code 2.
```

**Comment by jastang** [comment]
Hi @notone0010, it looks like an authz issue with the robot token. Could you verify the following in your account:

1. The robot that you created a token for is assigned to a team (in the Team Assignments tab)
2. The team has a repository permission for `provider-ksyun` with role `Write` (in the Permissions tab)

If this doesn't resolve the authz issue, could you send me a temporary invite to your organization so I can debug further?

**Comment by notone0010** [comment]
> Hi @notone0010, it looks like an authz issue with the robot token. Could you verify the following in your account:
> 
> 1. The robot that you created a token for is assigned to a team (in the Team Assignments tab)
> 2. The team has a repository permission for `provider-ksyun` with role `Write` (in the Permissions tab)
> 
> If this doesn't resolve the authz issue, could you send me a temporary invite to your organization so I can debug further?

Hi @jastang , it works. thank you very much! 😆

**Comment by notone0010** [comment]
Hi, @jastang I need a new review for the new organization package, [kingsoftcloud/provider-ksyun](https://github.com/kingsoftcloud/provider-ksyun) that will be created as our official package. And the my upbound account name is **notone**, the upbound repository, **kingsoftcloud/provider-ksyun**.

Thanks.

**Comment by jastang** [comment]
> Hi, @jastang I need a new review for the new organization package, [kingsoftcloud/provider-ksyun](https://github.com/kingsoftcloud/provider-ksyun) that will be created as our official package. And the my upbound account name is **notone**, the upbound repository, **kingsoftcloud/provider-ksyun**.
> 
> Thanks.

@notone0010 Sounds good, we can move over to `kingsoftcloud` -- note that you won't be able to use your token created from `notone` and you'll need to repeat the steps here with a robot in the `kingsoftcloud` account.

**Comment by notone0010** [comment]
> > Hi, @jastang I need a new review for the new organization package, [kingsoftcloud/provider-ksyun](https://github.com/kingsoftcloud/provider-ksyun) that will be created as our official package. And the my upbound account name is **notone**, the upbound repository, **kingsoftcloud/provider-ksyun**.
> > Thanks.
> 
> @notone0010 Sounds good, we can move over to `kingsoftcloud` -- note that you won't be able to use your token created from `notone` and you'll need to repeat the steps here with a robot in the `kingsoftcloud` account.

@jastang Yes, I used a robot token from `kingsoftcloud organization`, and it works successfully in Github Actions. I have tested it. Finally, does it need the reviews to public the `kingsoftcloud/provider-ksyun` package?

**Comment by jastang** [comment]
@notone0010 we are all set -- I have set the new repository to auto-publish. when you push your next release tag it'll generate a listing.
